{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-gitops-secrets-controller.serviceAccountName" . }}
  labels:
    {{- include "k8s-gitops-secrets-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
{{- if .Values.namespaced }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-gitops-secrets-controller.serviceAccountName" . }}
  labels:
    {{- include "k8s-gitops-secrets-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
{{- if .Values.namespaced }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-gitops-secrets-controller.serviceAccountName" . }}
  labels:
    {{- include "k8s-gitops-secrets-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-gitops-secrets-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.namespaced }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "k8s-gitops-secrets-controller.serviceAccountName" . }}
{{- end }}

