# permissions for end users to view keyencryptionkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyencryptionkeypolicies-viewer-role
rules:
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies/status
  verbs:
  - get
