
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets/status
  verbs:
  - get
  - patch
  - update
