# permissions for end users to view sealedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealedsecret-viewer-role
rules:
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rustrial.org
  resources:
  - sealedsecrets/status
  verbs:
  - get
