# permissions for end users to edit sealedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealedsecret-editor-role
rules:
- apiGroups:
  - secrets.rustrial.org
  resources:
  - sealedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rustrial.org
  resources:
  - sealedsecrets/status
  verbs:
  - get
