# permissions for end users to view keyencryptionkeypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keyencryptionkeypolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-gitops-secrets
    app.kubernetes.io/part-of: k8s-gitops-secrets
    app.kubernetes.io/managed-by: kustomize
  name: keyencryptionkeypolicy-viewer-role
rules:
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.rustrial.org
  resources:
  - keyencryptionkeypolicies/status
  verbs:
  - get
