apiVersion: secrets.rustrial.org/v1beta1
kind: SealedSecret
metadata:
  name: sealedsecret-sample
  namespace: default
spec:
  metadata:
    labels:
      my-label: label-value
    annotations:
      my-annotation: annotation-value
  encryptedData:
    hello:
    - keyEncryptionKeyId: arn:aws:kms:eu-central-1:000000000000:key/00000000-0000-0000-0000-000000000000
      awsKms:
        encryptionAlgorithm: AES_256
        nonce: hzxJEnrPLXq11FVw
        version: 1
      cipherText: IxgpY1AVDdajA7LhZoJK63hLc+ko
      dataEncryptionKey: QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE=
    hello2:
    - keyEncryptionKeyId: arn:aws:kms:eu-central-1:000000000000:key/00000000-0000-0000-0000-000000000000
      awsKms:
        encryptionAlgorithm: AES_256
        nonce: VdNt1mbRKADsJ3He
        version: 1
      cipherText: RINUqJOZhV2JqvsTjofiaD9+B3xO
      dataEncryptionKey: QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE=