apiVersion: secrets.rustrial.org/v1beta1
kind: SealedSecret
metadata:
  labels:
    app.kubernetes.io/name: sealedsecret
    app.kubernetes.io/instance: sealedsecret-sample
    app.kubernetes.io/part-of: k8s-gitops-secrets
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-gitops-secrets
  name: sealedsecret-sample
spec:
  # TODO(user): Add fields here
