name: build

on:
  pull_request:
  push:
    branches:
      - main
      - "*"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.12.0"
          image: "kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9"
      - name: Setup Helm
        uses: fluxcd/pkg/actions/helm@main
        with:
          version: "3.8.1"
      - name: Setup Kustomize
        uses: fluxcd/pkg/actions/kustomize@main
        with:
          version: "4.5.4"
      - name: Setup Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.2
        with:
          version: "3.3.0"
      - name: Setup Kubectl
        uses: fluxcd/pkg/actions/kubectl@main
        with:
          version: "1.23.4"
      - name: Run tests
        run: make test
        env:
          KUBEBUILDER_ASSETS: /usr/local/kubebuilder/bin
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Install from local image
        run: ./.github/install.sh helm
        env:
          KUBEBUILDER_ASSETS: /usr/local/kubebuilder/bin
      - name: Run e2e tests
        run: ./.github/e2e-tests.sh
        env:
          KUBEBUILDER_ASSETS: /usr/local/kubebuilder/bin
      - name: Logs
        continue-on-error: true
        run: |
          kubectl -n k8s-gitops-secrets-system logs deploy/k8s-gitops-secrets-controller-manager
      - name: Debug failure
        continue-on-error: true
        if: failure()
        run: |
          which kubectl
          kubectl version
          echo "-----------------------------------------------"
          kubectl -n k8s-gitops-secrets-system get all || true
          echo "-----------------------------------------------"
          kubectl -n k8s-gitops-secrets-system get sealedsecrets/aws-kms-secret -o yaml || true
          echo "-----------------------------------------------"
          kubectl -n k8s-gitops-secrets-system get pods -o yaml || true
          echo "-----------------------------------------------"
          kubectl -n k8s-gitops-secrets-system logs deploy/k8s-gitops-secrets-controller-manager
          echo "-----------------------------------------------"
      - name: Build seals CLI for all platforms
        run: make cli
